# NAMING
package_name: cnn
pipeline_name: cnn_pipeline

# MODEL PERSISTING
pipeline_save_file: cnn_pipeline_output.pkl
model_save_file: cnn_model.h5
classes_save_file: classes.pkl
encoder_save_file: encoder.pkl

# DATA
data_folder: plant_seedlings_v2
image_size: 150
valid_image_extensions:
  - .png
  - .jpg
test_size: 0.3
seed: 101
batch_size: 10
data_columns:
  - image
  - target

# MODEL FITTING
epochs: 10

