# APP
package_name: cnn
pipeline_name: cnn_pipeline
## model persisting
pipeline_save_file: cnn_pipeline_output.pkl
model_save_file: cnn_model.h5
classes_save_file: classes.pkl
encoder_save_file: encoder.pkl

# DATA
data_folder_name: plant_seedlings_v2
image_size: 150
valid_image_extensions:
  - .png
  - .jpg
test_size: 0.2
seed: 101
data_columns:
  - image
  - target

# MODEL
batch_size: 10
epochs: 10
learning_rate: 0.0001
loss: binary_crossentropy
metrics:
  - accuracy
validation_split: 10
## callbacks
checkpoint_monitor: acc
checkpoint_mode: max
reducelr_monitor: acc
reducelr_factor: 0.5
reducelr_patience: 2
reducelr_mode: max
reducelr_minlr: 0.00001

